[package]
name = "rgui-macros"
description = "rgui 过程宏——html! HTML 声明式宏、派生宏（WidgetSpec、AppMessage、PersistState）"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["gui", "macro", "derive", "dsl"]
categories = ["gui"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
rgui-core = { path = "../rgui-core" }
serde = { version = "1", features = ["derive"] }
ordered-float.workspace = true
