[package]
name = "one-icon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rgui = { path = "../../rgui", features = ["devtools"] }
rgui-core = { path = "../../rgui-core" }
rgui-devtools = { path = "../../rgui-devtools", features = ["html-hot-reload"] }
rgui-layout = { path = "../../rgui-layout" }
rgui-render = { path = "../../rgui-render" }
rgui-script = { path = "../../rgui-script" }
serde = "1"
