[package]
name = "one-wa-badge"
version = "0.1.0"
edition = "2021"

[dependencies]
rgui = { path = "../../rgui", features = ["devtools"] }
rgui-core = { path = "../../rgui-core" }
rgui-devtools = { path = "../../rgui-devtools", features = ["html-hot-reload"] }
rgui-layout = { path = "../../rgui-layout" }
rgui-render = { path = "../../rgui-render" }
rgui-script = { path = "../../rgui-script" }
serde = "1"
