[package]
name = "rgui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
[dependencies]
rgui-core.workspace = true
rgui-state.workspace = true
rgui-render.workspace = true
rgui-layout.workspace = true
rgui-style.workspace = true
rgui-platform.workspace = true
rgui-a11y.workspace = true
rgui-macros.workspace = true
rgui-components.workspace = true
rgui-devtools = { workspace = true, optional = true }
winit.workspace = true
[features]
default = ["vello-backend", "skia-backend"]
vello-backend = ["rgui-render/vello-backend"]
skia-backend = ["rgui-render/skia-backend"]
devtools = ["dep:rgui-devtools", "rgui-style/hot-reload"]
