[package]
name = "rgui-core"
description = "rgui 框架核心类型与 trait 定义——零平台依赖"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["gui", "widget", "core", "trait"]
categories = ["gui"]

[dependencies]
serde = { workspace = true, optional = true }
ordered-float.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
erased-serde.workspace = true
log.workspace = true

[dev-dependencies]
serde = { workspace = true }

[features]
default = []
serde = ["dep:serde", "ordered-float/serde"]
